name: Code coverage Builder
# To deal with https://securitylab.github.com/research/github-actions-preventing-pwn-requests
# we need to split this across two jobs. The part that writes to the pull request lives in
# ./coverage-report-workflow.yaml
on:
  pull_request:

jobs:
  build:
    permissions:
      contents: read
    name: Run code coverage analysis and reporting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout from Git
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v2
        name: Setup Java
        with:
          distribution: temurin
          java-version: 11
          cache: maven

      - name: Run tests with coverage
        run: mvn verify -Pcoverage